# Generated by Django 3.1.3 on 2020-11-24 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursovayaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='privilegies',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='count_material',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
