# Generated by Django 3.1.3 on 2020-11-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovayaapp', '0002_auto_20201124_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.BooleanField(default=0),
        ),
    ]
