# Generated by Django 3.1.3 on 2020-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovayaapp', '0003_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imag',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
