# Generated by Django 3.1.3 on 2020-11-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursovayaapp', '0004_material_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='login',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='privilegies',
        ),
    ]
